<a href="https://colab.research.google.com/github/pb-roshith/Dragon-resort-reactjs/blob/main/prakritifindingann.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import numpy as np
import pandas as pd
import tensorflow as tf
import keras

In [21]:
data = pd.read_excel('/content/prakritidata.xlsx')
data

Prakruti type Body Frame  Body weight   Skin    Hair   Teeth   Eyes  \
0           Vata       Thin          Low    Dry     Dry     Big  Small   
1          Pitha      Broad  Over Weight  Thick    Soft     Big  Thick   
2           Vata      Broad  Over Weight  Thick    Soft  Strong  Small   
3       Tridosha      Broad  Over Weight  Thick  Strong  Strong    Big   
4          Pitha     Medium     Moderate   Soft    Soft  Strong  Thick   
..           ...        ...          ...    ...     ...     ...    ...   
94    vata-Kapha      broad  Over Weight  Thick     Dry  Strong  Small   
95   pitha-Kapha       Thin  Over Weight   Soft    soft  Strong  Thick   
96      Tridosha       Thin          Low  Thick     Dry     Big  Thick   
97   pitha-Kapha     Medium  Over Weight   Soft    soft  Strong  Thick   
98      Tridosha      broad          Low  Thick     Dry     Big  Thick   

      Nails   Tongue Food Habits     Thirst  Bowl Physical Activities  \
0   Brittle  Cracked    Frequent   Variable   Dry         Very Active   
1      Soft      Red   Excessive  Excessive  Soft            Moderate   
2   Brittle  Cracked    Frequent   Variable   Dry         Very Active   
3      Soft      Red   Excessive  Excessive  Soft            Moderate   
4      Soft      Red   Excessive  Excessive  Soft            Moderate   
..      ...      ...         ...        ...   ...                 ...   
94  Brittle    White    frequent   Variable  Oily           Lethargic   
95     Soft      Red   Excessive   Variable  Oily           Lethargic   
96     Soft    White      Stable   Variable   Dry            Moderate   
97     Soft      Red   Excessive   Variable  Oily           Lethargic   
98     Soft    White      Stable   Variable   Dry            Moderate   

   Tolerance for Seasonal Weather Communication    Memory  \
0                 Cold Intolerant    Less Vocal      Slow   
1                 Heat Intolerant         Sharp  Moderate   
2                 Cold Intolerant     Talkative     Quick   
3                 Cold Intolerant     Talkative     Quick   
4                 Heat Intolerant         Sharp  Moderate   
..                            ...           ...       ...   
94                heat Intolerant     Talkative     Quick   
95                Cold Intolerant         Sharp  Moderate   
96                Cold Intolerant     Talkative     Quick   
97                Cold Intolerant         Sharp  Moderate   
98                Cold Intolerant     Talkative     Quick   

   Emotional Temperament     Pulse Body Temperature  
0             Aggressive  Moderate         Moderate  
1             Aggressive  Moderate             High  
2                Fearful    Feeble         Moderate  
3                Fearful    Feeble         Moderate  
4             Aggressive  Moderate              Low  
..                   ...       ...              ...  
94                  Calm  Moderate             High  
95                  Calm    Feeble         Moderate  
96               Fearful      Slow              Low  
97                  Calm  Moderate         Moderate  
98               Fearful    Feeble              Low  

[99 rows x 19 columns]

In [22]:
data.head()

Prakruti type Body Frame  Body weight   Skin    Hair   Teeth   Eyes  \
0          Vata       Thin          Low    Dry     Dry     Big  Small   
1         Pitha      Broad  Over Weight  Thick    Soft     Big  Thick   
2          Vata      Broad  Over Weight  Thick    Soft  Strong  Small   
3      Tridosha      Broad  Over Weight  Thick  Strong  Strong    Big   
4         Pitha     Medium     Moderate   Soft    Soft  Strong  Thick   

     Nails   Tongue Food Habits     Thirst  Bowl Physical Activities  \
0  Brittle  Cracked    Frequent   Variable   Dry         Very Active   
1     Soft      Red   Excessive  Excessive  Soft            Moderate   
2  Brittle  Cracked    Frequent   Variable   Dry         Very Active   
3     Soft      Red   Excessive  Excessive  Soft            Moderate   
4     Soft      Red   Excessive  Excessive  Soft            Moderate   

  Tolerance for Seasonal Weather Communication    Memory  \
0                Cold Intolerant    Less Vocal      Slow   
1                Heat Intolerant         Sharp  Moderate   
2                Cold Intolerant     Talkative     Quick   
3                Cold Intolerant     Talkative     Quick   
4                Heat Intolerant         Sharp  Moderate   

  Emotional Temperament     Pulse Body Temperature  
0            Aggressive  Moderate         Moderate  
1            Aggressive  Moderate             High  
2               Fearful    Feeble         Moderate  
3               Fearful    Feeble         Moderate  
4            Aggressive  Moderate              Low

In [23]:
data.tail()

Prakruti type Body Frame  Body weight   Skin  Hair   Teeth   Eyes    Nails  \
94    vata-Kapha      broad  Over Weight  Thick   Dry  Strong  Small  Brittle   
95   pitha-Kapha       Thin  Over Weight   Soft  soft  Strong  Thick     Soft   
96      Tridosha       Thin          Low  Thick   Dry     Big  Thick     Soft   
97   pitha-Kapha     Medium  Over Weight   Soft  soft  Strong  Thick     Soft   
98      Tridosha      broad          Low  Thick   Dry     Big  Thick     Soft   

   Tongue Food Habits    Thirst  Bowl Physical Activities  \
94  White    frequent  Variable  Oily           Lethargic   
95    Red   Excessive  Variable  Oily           Lethargic   
96  White      Stable  Variable   Dry            Moderate   
97    Red   Excessive  Variable  Oily           Lethargic   
98  White      Stable  Variable   Dry            Moderate   

   Tolerance for Seasonal Weather Communication    Memory  \
94                heat Intolerant     Talkative     Quick   
95                Cold Intolerant         Sharp  Moderate   
96                Cold Intolerant     Talkative     Quick   
97                Cold Intolerant         Sharp  Moderate   
98                Cold Intolerant     Talkative     Quick   

   Emotional Temperament     Pulse Body Temperature  
94                  Calm  Moderate             High  
95                  Calm    Feeble         Moderate  
96               Fearful      Slow              Low  
97                  Calm  Moderate         Moderate  
98               Fearful    Feeble              Low

In [24]:
from sklearn.preprocessing import OrdinalEncoder
encoder=OrdinalEncoder()
lis=[['Prakruti type','Body Frame','Body weight','Skin','Hair','Teeth','Eyes','Nails','Tongue','Food Habits','Thirst','Bowl','Physical Activities','Tolerance for Seasonal Weather','Communication','Memory','Emotional Temperament','Pulse','Body Temperature']]
for i in lis:
    data[i]=encoder.fit_transform(data[i])

In [25]:
from sklearn.model_selection import train_test_split
x = data.iloc[:, 1:19].values
y = data.iloc[:, 1].values
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [26]:
x

array([[2., 0., 0., ..., 0., 1., 2.],
       [0., 2., 2., ..., 0., 1., 0.],
       [0., 2., 2., ..., 2., 0., 2.],
       ...,
       [2., 0., 2., ..., 2., 3., 1.],
       [1., 2., 1., ..., 1., 1., 2.],
       [3., 0., 2., ..., 2., 0., 1.]])

In [27]:
y

array([2., 0., 0., 0., 1., 2., 2., 0., 1., 0., 2., 2., 0., 0., 1., 1., 0.,
       0., 1., 0., 2., 0., 2., 1., 0., 1., 2., 2., 2., 3., 1., 2., 3., 3.,
       1., 1., 3., 2., 2., 0., 1., 1., 1., 3., 2., 2., 0., 1., 2., 3., 3.,
       2., 2., 0., 1., 2., 3., 3., 2., 2., 0., 1., 2., 3., 3., 2., 2., 0.,
       1., 3., 1., 2., 1., 3., 2., 2., 3., 1., 2., 1., 3., 2., 2., 3., 1.,
       2., 1., 3., 2., 2., 3., 1., 2., 1., 3., 2., 2., 1., 3.])

In [28]:
x_train

array([[3., 2., 2., ..., 1., 3., 1.],
       [2., 1., 3., ..., 2., 0., 3.],
       [0., 2., 2., ..., 2., 0., 2.],
       ...,
       [3., 2., 2., ..., 1., 0., 2.],
       [1., 2., 0., ..., 1., 1., 0.],
       [2., 1., 0., ..., 2., 1., 0.]])

In [29]:
y_train

array([3., 2., 0., 2., 2., 2., 2., 3., 2., 3., 0., 3., 2., 1., 2., 2., 1.,
       3., 3., 2., 0., 1., 1., 1., 1., 1., 0., 1., 2., 2., 3., 2., 2., 1.,
       2., 3., 2., 1., 1., 2., 2., 2., 2., 3., 1., 2., 3., 1., 1., 2., 0.,
       3., 3., 2., 1., 3., 2., 1., 1., 1., 1., 2., 2., 0., 0., 2., 2., 0.,
       1., 3., 3., 0., 3., 0., 2., 0., 3., 1., 2.])

In [55]:
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Dense(units=8, activation='relu'))
model.add(tf.keras.layers.Dense(units=8, activation='relu'))
model.add(tf.keras.layers.Dense(units=1))
model.compile(optimizer='adam', loss='mean_squared_error')

In [57]:
model.fit(x_train, y_train, batch_size=12, epochs=1000, verbose=1)

Epoch 1/1000
7/7 [==============================] - 0s 2ms/step - loss: 3.5373e-06
Epoch 2/1000
7/7 [==============================] - 0s 2ms/step - loss: 3.8361e-06
Epoch 3/1000
7/7 [==============================] - 0s 2ms/step - loss: 3.6453e-06
Epoch 4/1000
7/7 [==============================] - 0s 2ms/step - loss: 3.7211e-06
Epoch 5/1000
7/7 [==============================] - 0s 2ms/step - loss: 3.4383e-06
Epoch 6/1000
7/7 [==============================] - 0s 3ms/step - loss: 3.5997e-06
Epoch 7/1000
7/7 [==============================] - 0s 3ms/step - loss: 3.6624e-06
Epoch 8/1000
7/7 [==============================] - 0s 2ms/step - loss: 4.1290e-06
Epoch 9/1000
7/7 [==============================] - 0s 3ms/step - loss: 3.6601e-06
Epoch 10/1000
7/7 [==============================] - 0s 3ms/step - loss: 3.4035e-06
Epoch 11/1000
7/7 [==============================] - 0s 3ms/step - loss: 3.6450e-06
Epoch 12/1000
7/7 [==============================] - 0s 3ms/step - loss: 3.2466e-06
E

In [58]:
from sklearn.metrics import mean_squared_error
y_pred = model.predict(x_test)

1/1 [==============================] - 0s 57ms/step


In [59]:
print(f"mean squared error : {mean_squared_error(y_pred, y_test)}")

mean squared error : 0.0021689812118235244
